In [ ]:
import numpy as np
np.array([[1,2,3],[4,5,6]]).tolist()
print(array.reshape)

In [86]:
print()
import numpy as np

m = np.arange(6).reshape(2,3)
print (m)
youssef =  np.trace(m)

print(youssef)


[[0 1 2]
 [3 4 5]]
4


In [5]:
import numpy as np
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

In [8]:
import numpy as np
a = np.array([[4,5,6]])
b = x.mean()
print(b)

5.0
